version: '3'

services:
  backend:
    build: './MSD'
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - './MSD:/usr/src/app'
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  frontend:
    build: './MSDV'
    volumes:
      - './MSDV:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5173:5173'

  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8081:8080"

  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=WP-Park
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'

volumes:
  pgdata:
