# Generated by Django 4.2.3 on 2023-08-13 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=10)),
                ('times', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=3)),
                ('postal_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('reason_of_visiting', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chronic_conditions', models.ManyToManyField(blank=True, related_name='chronic_conditions_patient', to='patient.chroniccondition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'DR'}, related_name='doctor_patient', to=settings.AUTH_USER_MODEL)),
                ('medications', models.ManyToManyField(blank=True, related_name='medications_patient', to='patient.medication')),
                ('nurses', models.ManyToManyField(blank=True, limit_choices_to={'role': 'NR'}, related_name='nurse_patient', to=settings.AUTH_USER_MODEL)),
                ('surgeries', models.ManyToManyField(blank=True, related_name='surgeries_patient', to='patient.surgery')),
            ],
        ),
    ]
