# Generated by Django 4.2.3 on 2023-08-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='chronic_conditions',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surgeries',
        ),
        migrations.DeleteModel(
            name='ChronicCondition',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Surgery',
        ),
    ]
