# Generated by Django 4.2.3 on 2023-09-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_fhir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirmeasurement',
            name='movement',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fhirmeasurement',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
    ]
